### ISSUE TITLE
Eleastic Search version 5.6

### ISSUE THREAD

**Issue by robertlemke** [flownative/localbeach-phar#9]
In GitLab by @markusguenther on Jul 10, 2019, 14:08

When using the elasticsearch yaml configuration from the neos.neosio setup with the little adjustment of the image version. The container never succeeds. The container always quits with code 78.

Other images seems not to be available (5.5. or 6.0)

**yaml**:

```
  elasticsearch:
    image: ${BEACH_ELASTICSEARCH_IMAGE:-flownative/elasticsearch}:${BEACH_ELASTICSEARCH_IMAGE_VERSION:-5.6}
    container_name: ${BEACH_PROJECT_NAME:?Please specify a Beach project name as BEACH_PROJECT_NAME}_elasticsearch
    networks:
      - local_beach
    volumes:
      - ./.LocalBeach/elasticsearch:/data
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=${ELASTICSEARCH_CLUSTER_NAME:-elasticsearch-default}
      - ELASTICSEARCH_NODE_MASTER=${ELASTICSEARCH_NODE_MASTER:-true}
      - ELASTICSEARCH_NODE_DATA=${ELASTICSEARCH_NODE_DATA:-true}
      - ELASTICSEARCH_NODE_NAME=${ELASTICSEARCH_NODE_NAME:-}
      - ELASTICSEARCH_HTTP_ENABLE=${ELASTICSEARCH_HTTP_ENABLE:-true}
      - ELASTICSEARCH_HTTP_CORS_ENABLE=${ELASTICSEARCH_HTTP_CORS_ENABLE:-true}
      - ELASTICSEARCH_HTTP_CORS_ALLOW_ORIGIN=${ELASTICSEARCH_HTTP_CORS_ALLOW_ORIGIN:-*}
```

**The log returns**:
```
foo_elasticsearch   | [2019-07-10T11:57:17,496][INFO ][o.e.p.PluginsService     ] [pWtXPUo] loaded module [aggs-matrix-stats]
foo_elasticsearch   | [2019-07-10T11:57:17,498][INFO ][o.e.p.PluginsService     ] [pWtXPUo] loaded module [ingest-common]
foo_elasticsearch   | [2019-07-10T11:57:17,499][INFO ][o.e.p.PluginsService     ] [pWtXPUo] loaded module [lang-expression]
foo_elasticsearch   | [2019-07-10T11:57:17,500][INFO ][o.e.p.PluginsService     ] [pWtXPUo] loaded module [lang-groovy]
foo_elasticsearch   | [2019-07-10T11:57:17,500][INFO ][o.e.p.PluginsService     ] [pWtXPUo] loaded module [lang-mustache]
foo_elasticsearch   | [2019-07-10T11:57:17,504][INFO ][o.e.p.PluginsService     ] [pWtXPUo] loaded module [lang-painless]
foo_elasticsearch   | [2019-07-10T11:57:17,506][INFO ][o.e.p.PluginsService     ] [pWtXPUo] loaded module [parent-join]
foo_elasticsearch   | [2019-07-10T11:57:17,506][INFO ][o.e.p.PluginsService     ] [pWtXPUo] loaded module [percolator]
foo_elasticsearch   | [2019-07-10T11:57:17,507][INFO ][o.e.p.PluginsService     ] [pWtXPUo] loaded module [reindex]
foo_elasticsearch   | [2019-07-10T11:57:17,508][INFO ][o.e.p.PluginsService     ] [pWtXPUo] loaded module [transport-netty3]
foo_elasticsearch   | [2019-07-10T11:57:17,508][INFO ][o.e.p.PluginsService     ] [pWtXPUo] loaded module [transport-netty4]
foo_elasticsearch   | [2019-07-10T11:57:17,509][INFO ][o.e.p.PluginsService     ] [pWtXPUo] no plugins loaded
foo_elasticsearch   | [2019-07-10T11:57:20,421][INFO ][o.e.d.DiscoveryModule    ] [pWtXPUo] using discovery type [zen]
foo_elasticsearch   | [2019-07-10T11:57:21,181][INFO ][o.e.c.u.IndexFolderUpgrader] [foo-1562759694/KqxG4CDxRTmGUCUG_xOJow] upgrading [/data/data/foo/nodes/0/indices/foo-1562759694] to new naming convention
foo_elasticsearch   | [2019-07-10T11:57:21,191][INFO ][o.e.c.u.IndexFolderUpgrader] [foo-1562759694/KqxG4CDxRTmGUCUG_xOJow] moved from [/data/data/foo/nodes/0/indices/foo-1562759694] to [/data/data/foo/nodes/0/indices/KqxG4CDxRTmGUCUG_xOJow]
foo_elasticsearch   | [2019-07-10T11:57:21,430][INFO ][o.e.n.Node               ] initialized
foo_elasticsearch   | [2019-07-10T11:57:21,431][INFO ][o.e.n.Node               ] [pWtXPUo] starting ...
foo_elasticsearch   | [2019-07-10T11:57:21,717][INFO ][o.e.t.TransportService   ] [pWtXPUo] publish_address {172.26.0.12:9300}, bound_addresses {127.0.0.1:9300}, {172.26.0.12:9300}
foo_elasticsearch   | [2019-07-10T11:57:21,743][INFO ][o.e.b.BootstrapChecks    ] [pWtXPUo] bound or publishing to a non-loopback address, enforcing bootstrap checks
foo_elasticsearch   | ERROR: [1] bootstrap checks failed
foo_elasticsearch   | [1]: memory locking requested for elasticsearch process but memory is not locked
foo_elasticsearch   | [2019-07-10T11:57:21,752][INFO ][o.e.n.Node               ] [pWtXPUo] stopping ...
foo_elasticsearch   | [2019-07-10T11:57:21,823][INFO ][o.e.n.Node               ] [pWtXPUo] stopped
foo_elasticsearch   | [2019-07-10T11:57:21,824][INFO ][o.e.n.Node               ] [pWtXPUo] closing ...
foo_elasticsearch   | [2019-07-10T11:57:21,845][INFO ][o.e.n.Node               ] [pWtXPUo] closed
foo_elasticsearch exited with code 78
```

**Comment by robertlemke** [comment]
In GitLab by @markusguenther on Jul 10, 2019, 14:11

changed the description

**Comment by robertlemke** [comment]
In GitLab by @markusguenther on Jul 10, 2019, 14:12

changed the description

**Comment by robertlemke** [comment]
In GitLab by @markusguenther on Jul 10, 2019, 15:25

Ok Karsten had some additional Configs and then it is working.

```
elasticsearch:
    image: ${BEACH_ELASTICSEARCH_IMAGE:-flownative/elasticsearch}:${BEACH_ELASTICSEARCH_IMAGE_VERSION:-5.6}
    container_name: ${BEACH_PROJECT_NAME:?Please specify a Beach project name as BEACH_PROJECT_NAME}_elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xmx2048m -Xms2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - local_beach
    volumes:
      - ./.LocalBeach/elasticsearch:/data
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=${ELASTICSEARCH_CLUSTER_NAME:-elasticsearch-default}
      - ELASTICSEARCH_NODE_MASTER=${ELASTICSEARCH_NODE_MASTER:-true}
      - ELASTICSEARCH_NODE_DATA=${ELASTICSEARCH_NODE_DATA:-true}
      - ELASTICSEARCH_NODE_NAME=${ELASTICSEARCH_NODE_NAME:-}
      - ELASTICSEARCH_HTTP_ENABLE=${ELASTICSEARCH_HTTP_ENABLE:-true}
      - ELASTICSEARCH_HTTP_CORS_ENABLE=${ELASTICSEARCH_HTTP_CORS_ENABLE:-true}
      - ELASTICSEARCH_HTTP_CORS_ALLOW_ORIGIN=${ELASTICSEARCH_HTTP_CORS_ALLOW_ORIGIN:-*}
```
